server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/monitoramento;
    index teste.html;

    location / {
        try_files $uri $uri/ /teste.html;
    }

    location ~* \.(json|geojson)$ {
        default_type application/json;
        gzip_static on;
        gzip_vary on;
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }
}
